services:

  AxeptiocookiesAddon\API\Client\Client:
    class: AxeptiocookiesAddon\API\Client\Client
    public: true
    arguments:
      - '@AxeptiocookiesAddon\API\Response\Factory\ResponseFactory'

  AxeptiocookiesAddon\Service\ProjectService:
    class: AxeptiocookiesAddon\Service\ProjectService
    public: true
    arguments:
      - '@AxeptiocookiesAddon\API\Client\Client'

  AxeptiocookiesAddon\Service\ModuleService:
    class: AxeptiocookiesAddon\Service\ModuleService
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Repository\ModuleRepository'
      - '@AxeptiocookiesAddon\API\Client\Client'

  AxeptiocookiesAddon\Validator\ConfigurationValidator:
    class: AxeptiocookiesAddon\Validator\ConfigurationValidator
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Repository\ConfigurationRepository'

  AxeptiocookiesAddon\Service\ConfigurationService:
    class: AxeptiocookiesAddon\Service\ConfigurationService
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Repository\ConfigurationRepository'
      - '@AxeptiocookiesAddon\Service\ProjectService'
      - '@AxeptiocookiesAddon\Service\ModuleService'
      - '@AxeptiocookiesAddon\Validator\ConfigurationValidator'
      - '@AxeptiocookiesAddon\Service\HookService'

  AxeptiocookiesAddon\Cache\ProjectCache:
    class: AxeptiocookiesAddon\Cache\ProjectCache
    public: true

  AxeptiocookiesAddon\Service\HookService:
    class: AxeptiocookiesAddon\Service\HookService
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Cache\ProjectCache'
      - '@AxeptiocookiesAddon\Service\ProjectService'
      - '@AxeptiocookiesAddon\Repository\ConfigurationRepository'
      - '@AxeptiocookiesAddon\Service\ModuleService'

  AxeptiocookiesAddon\Service\CookieService:
    class: AxeptiocookiesAddon\Service\CookieService
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Service\HookService'

  AxeptiocookiesAddon\API\Response\Factory\ResponseFactory:
    class: AxeptiocookiesAddon\API\Response\Factory\ResponseFactory
    public: true