services:
  AxeptiocookiesAddon\Update\UpdateHandler:
    class: AxeptiocookiesAddon\Update\UpdateHandler
    public: true
    arguments:
      - '@AxeptiocookiesAddon\Service\ProjectService'
      - '@AxeptiocookiesAddon\Service\ConfigurationService'
