imports:
  - { resource: partials/repository.yml }
  - { resource: partials/service.yml }
  - { resource: partials/update.yml }

services:
  axeptiocookies:
    class: 'Axeptiocookies'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'axeptiocookies'